### ISSUE TITLE
Broadcast Buttons

### ISSUE THREAD

**Issue by ziyadk1997** [ziyadk1997/The-Food-Website#1]
Ya gama3a lama bagy ageeb el broadcast ID el saved fl button awel ma badoos 3aleeh beyegy 8alot byegy ma3ah restaurantID = " byegy keda
a48a01e1-d4e4-42d3-bc9d-59fe0dbbf56erestaurantid =

**Comment by zare3** [comment]
Btgeeb el broadcast id ezaii?
